/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.pvoe.fraccion.formas;

import java.awt.Color;
import uam.pvoe.fraccion.clases.Fraccion;
import uam.pvoe.fraccion.operaciones.Generador;
import uam.pvoe.fraccion.operaciones.Operador;

/**
 *
 * @author Kranlo
 */
public class Pantalla extends javax.swing.JFrame {

    private Fraccion f1,f2,fRes = new Fraccion(); 
    Operador op;
    
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        inicializar();
    }
    
    private void inicializar(){
        Generador gen = new Generador();
        f1 = gen.generar();
        f2 = gen.generar();
        op = new Operador(f1,f2);
        fResNumerador.setText("");
        fResDenominador.setText("");
        
        f1Numerador.setText(""+f1.getNumerador());
        f1Denominador.setText(""+f1.getDenominador());
        
        f2Numerador.setText(""+f2.getNumerador());
        f2Denominador.setText(""+f2.getDenominador()); 
        
        f1Numerador.setBackground(Color.LIGHT_GRAY);
        f1Denominador.setBackground(Color.LIGHT_GRAY);
        f2Numerador.setBackground(Color.LIGHT_GRAY);
        f2Denominador.setBackground(Color.LIGHT_GRAY);
        
        f1Numerador.setEditable(false);
        f1Denominador.setEditable(false);
        f2Numerador.setEditable(false);
        f2Denominador.setEditable(false);
        
        fResNumerador.setBackground(Color.WHITE);
        fResDenominador.setBackground(Color.WHITE);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f1Numerador = new javax.swing.JTextField();
        f1Denominador = new javax.swing.JTextField();
        f2Numerador = new javax.swing.JTextField();
        f2Denominador = new javax.swing.JTextField();
        lbIgual = new javax.swing.JLabel();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        fResNumerador = new javax.swing.JTextField();
        fResDenominador = new javax.swing.JTextField();
        lblOperacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        f1Numerador.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        f1Denominador.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        f2Numerador.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        f2Denominador.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        lbIgual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbIgual.setText("=");

        btnSuma.setText("SUMA");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnResta.setText("RESTA");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnMultiplicacion.setText("MULT");
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });

        btnDivision.setText("DIV");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        fResNumerador.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fResNumerador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fResNumeradorKeyReleased(evt);
            }
        });

        fResDenominador.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fResDenominador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fResDenominadorKeyReleased(evt);
            }
        });

        lblOperacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblOperacion.setText("+");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(f1Denominador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f1Numerador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(f2Denominador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f2Numerador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSuma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMultiplicacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDivision)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fResNumerador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fResDenominador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lblOperacion)
                .addGap(140, 140, 140)
                .addComponent(lbIgual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f1Numerador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f2Numerador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fResNumerador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIgual)
                    .addComponent(lblOperacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f1Denominador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f2Denominador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fResDenominador, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuma)
                    .addComponent(btnResta)
                    .addComponent(btnMultiplicacion)
                    .addComponent(btnDivision)
                    .addComponent(btnReset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        inicializar();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        lblOperacion.setText("+");
        if(op.suma(fRes)){
            fResNumerador.setBackground(Color.GREEN);
            fResDenominador.setBackground(Color.GREEN);
        } else {
            fResNumerador.setBackground(Color.RED);
            fResDenominador.setBackground(Color.RED); 
            System.out.println("Resultado incorrecto!");
        }       
    }//GEN-LAST:event_btnSumaActionPerformed

    private void fResNumeradorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fResNumeradorKeyReleased
        try {
            fResNumerador.setBackground(Color.WHITE);
            fResDenominador.setBackground(Color.WHITE);
            fRes.setNumerador(Integer.parseInt(fResNumerador.getText()));
        } catch (NumberFormatException e) {
            System.out.println("Ingrese un numero valido para el numerador");
            // fResNumerador.setBackground(Color.BLUE);
        }
    }//GEN-LAST:event_fResNumeradorKeyReleased

    private void fResDenominadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fResDenominadorKeyReleased
        try {
            fResDenominador.setBackground(Color.WHITE);
            fResNumerador.setBackground(Color.WHITE);
            fRes.setDenominador(Integer.parseInt(fResDenominador.getText()));
        } catch (NumberFormatException e) {
            System.out.println("Ingrese un numero valido para el numerador");
            // fResDenominador.setBackground(Color.BLUE);
        }
    }//GEN-LAST:event_fResDenominadorKeyReleased

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        lblOperacion.setText("-");
        if(op.resta(fRes)){
            fResNumerador.setBackground(Color.GREEN);
            fResDenominador.setBackground(Color.GREEN);
            System.out.println("Resultado correcto!");
            
        } else {
            fResNumerador.setBackground(Color.RED);
            fResDenominador.setBackground(Color.RED);  
            System.out.println("Resultado incorrecto!");
        } 
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        lblOperacion.setText("X");
        if(op.multiplicacion(fRes)){
            fResNumerador.setBackground(Color.GREEN);
            fResDenominador.setBackground(Color.GREEN);
            System.out.println("Resultado correcto!");
        } else {
            fResNumerador.setBackground(Color.RED);
            fResDenominador.setBackground(Color.RED);  
            System.out.println("Resultado incorrecto!");
        } 
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        lblOperacion.setText("%");
        if(op.division(fRes)){
            fResNumerador.setBackground(Color.GREEN);
            fResDenominador.setBackground(Color.GREEN);
            System.out.println("Resultado correcto!");
        } else {
            fResNumerador.setBackground(Color.RED);
            fResDenominador.setBackground(Color.RED);  
            System.out.println("Resultado incorrecto!");
        }
    }//GEN-LAST:event_btnDivisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JTextField f1Denominador;
    private javax.swing.JTextField f1Numerador;
    private javax.swing.JTextField f2Denominador;
    private javax.swing.JTextField f2Numerador;
    private javax.swing.JTextField fResDenominador;
    private javax.swing.JTextField fResNumerador;
    private javax.swing.JLabel lbIgual;
    private javax.swing.JLabel lblOperacion;
    // End of variables declaration//GEN-END:variables
}
