/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.plantillas.formas;

import uam.pvoe.sw.plantillas.compartido.Compartido;
import uam.pvoe.sw.plantillas.operaciones.DatosUsuario;

/**
 *
 * @author josue
 */
public class MenuFrm extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrm
     */
    public MenuFrm() {
        initComponents();
        cargarDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();
        btnOpcionA = new javax.swing.JButton();
        btnOpcionB = new javax.swing.JButton();
        btnOpcionC = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        lblBienvenido.setText("Bienvenido");

        lblNombre.setText("jLabel2");

        pnlContenedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Menú Principal"));

        btnOpcionA.setText("jButton1");
        btnOpcionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionAActionPerformed(evt);
            }
        });

        btnOpcionB.setText("jButton2");
        btnOpcionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionBActionPerformed(evt);
            }
        });

        btnOpcionC.setText("jButton1");
        btnOpcionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpcionA, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(btnOpcionB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOpcionC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 481, Short.MAX_VALUE))
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnOpcionA)
                .addGap(48, 48, 48)
                .addComponent(btnOpcionB)
                .addGap(52, 52, 52)
                .addComponent(btnOpcionC)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        lblDescripcion.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBienvenido)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombre)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBienvenido)
                    .addComponent(lblNombre))
                .addGap(31, 31, 31)
                .addComponent(lblDescripcion)
                .addGap(39, 39, 39)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionAActionPerformed
        if(Compartido.tipoUsuario.compareTo("admin")==0){
            this.dispose();
            ConsultaResultadosFrm consulta = new ConsultaResultadosFrm();
            consulta.setVisible(true);
        }else{
            this.dispose();
            PreguntaFrm pregunta = new PreguntaFrm();
            pregunta.setVisible(true);
        }
    }//GEN-LAST:event_btnOpcionAActionPerformed

    private void btnOpcionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionBActionPerformed
        if(Compartido.tipoUsuario.compareTo("admin")==0){
            System.out.println("Otra opción del Administrador");
        }else{
            System.out.println("Otra opción del Usuario");
        }
    }//GEN-LAST:event_btnOpcionBActionPerformed

    private void btnOpcionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionCActionPerformed
        System.out.println("Otra opción solo del usuario");
    }//GEN-LAST:event_btnOpcionCActionPerformed

    
    public void cargarDatos(){
        
        DatosUsuario datos = new DatosUsuario();
        datos.nombreUsuario(Compartido.login);
        
        String descripcion = datos.descripcion(Compartido.tipoUsuario);
        
        lblNombre.setText(Compartido.nombreUsuario);
        lblDescripcion.setText(descripcion);
        
        if(Compartido.tipoUsuario.compareTo("admin")==0){
            btnOpcionA.setText("Consultar Resultados");
            btnOpcionB.setText("Otra Opción de Administrador");
            btnOpcionC.setVisible(false);
        }else{
            btnOpcionA.setText("Comenzar Prueba");
            btnOpcionB.setText("Otra Opción de Usuario 1");
            btnOpcionC.setText("Otra Opción de Usuario 2");
            }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpcionA;
    private javax.swing.JButton btnOpcionB;
    private javax.swing.JButton btnOpcionC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
