/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.plantillas.formas;

import java.util.LinkedList;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import uam.pvoe.sw.plantillas.clases.Pregunta;
import uam.pvoe.sw.plantillas.compartido.Compartido;
import uam.pvoe.sw.plantillas.operaciones.OperacionesCuestionario;



/**
 *
 * @author josue
 */
public class PreguntaFrm extends javax.swing.JFrame {

    Pregunta pregunta;
    /**
     * Creates new form PreguntaFrm
     */
    public PreguntaFrm() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();
        lblTituloPregunta = new javax.swing.JLabel();
        pnlContenedorRespuesta = new javax.swing.JPanel();
        btnAvanzar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblTituloCuestionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));

        lblTitulo.setText("Bienvenido");

        lblPregunta.setText("Pregunta: ");

        lblTituloPregunta.setText("jLabel1");

        pnlContenedorRespuesta.setBorder(javax.swing.BorderFactory.createTitledBorder("Respuesta"));

        javax.swing.GroupLayout pnlContenedorRespuestaLayout = new javax.swing.GroupLayout(pnlContenedorRespuesta);
        pnlContenedorRespuesta.setLayout(pnlContenedorRespuestaLayout);
        pnlContenedorRespuestaLayout.setHorizontalGroup(
            pnlContenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        pnlContenedorRespuestaLayout.setVerticalGroup(
            pnlContenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        btnAvanzar.setText("jButton1");
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });

        lblNombre.setText("jLabel1");

        lblTituloCuestionario.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPregunta)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblNombre))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lblTituloPregunta)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlContenedorRespuesta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAvanzar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(lblTituloCuestionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addComponent(lblTituloCuestionario)
                .addGap(18, 18, 18)
                .addComponent(lblPregunta)
                .addGap(18, 18, 18)
                .addComponent(lblTituloPregunta)
                .addGap(18, 18, 18)
                .addComponent(pnlContenedorRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnAvanzar)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        if(Compartido.preguntaActual != Compartido.totalPreguntas){
            Compartido.preguntaActual++;
            this.dispose();
            PreguntaFrm preguntaFrm = new PreguntaFrm();
            preguntaFrm.setVisible(true);
        }else{
            this.dispose();
            ResultadoFrm resultadoFrm = new ResultadoFrm();
            resultadoFrm.setVisible(true);
        }       
    }//GEN-LAST:event_btnAvanzarActionPerformed

      
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreguntaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreguntaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreguntaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreguntaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreguntaFrm().setVisible(true);
            }
        });
    }

    public void cargarPregunta(){
        int preguntaActual = Compartido.preguntaActual;
        OperacionesCuestionario op = new OperacionesCuestionario();
        Pregunta pregunta = op.regresaPregunta(preguntaActual);
        lblTituloPregunta.setText(pregunta.getPregunta());
        lblPregunta.setText("Pregunta " + preguntaActual + " de " + Compartido.totalPreguntas);
        if(preguntaActual < Compartido.totalPreguntas)
            btnAvanzar.setText("Siguiente");      
        if(pregunta.getTipoPregunta().compareTo("CB") == 0){
            construyeComboBox(pregunta);
        } else if(pregunta.getTipoPregunta().compareTo("RB") == 0){
            construyeRadioButton(pregunta);
        }
    }
    
    public void construyeComboBox(Pregunta pregunta){
        JComboBox<String> listaRespuestas = new JComboBox<>();
        LinkedList<String> lista = pregunta.getListaOpciones();
        for (int i = 0; i < lista.size(); i++) {
            listaRespuestas.addItem(lista.get(i));
        }
        listaRespuestas.setSelectedIndex(0);
        
        // tamaño y posicion
        double ancho = listaRespuestas.getPreferredSize().getWidth();
        int iancho = (int)ancho+100;
        
        // indicar posicion y tamaño
        listaRespuestas.setBounds(160, 80, iancho, 40);
        
        // desplegar 
        pnlContenedorRespuesta.add(listaRespuestas);
        listaRespuestas.setVisible(true);
    }
    
    public void construyeRadioButton(Pregunta pregunta){
        ButtonGroup btnGrp = new ButtonGroup();
        LinkedList<String> lista = pregunta.getListaOpciones();
        
        int inicio = 30;
        for (int i = 0; i < lista.size(); i++) {
            JRadioButton btn = new JRadioButton();
            btn.setText(lista.get(i));
            btnGrp.add(btn);
            
            // tamaño y posicion 
            btn.setBounds(100,inicio,200,40);
        
            // Desplegar
            pnlContenedorRespuesta.add(btn);
            btn.setVisible(true);
  
            btn.setSelected(true);
            inicio += 30;
        }
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloCuestionario;
    private javax.swing.JLabel lblTituloPregunta;
    private javax.swing.JPanel pnlContenedorRespuesta;
    // End of variables declaration//GEN-END:variables
}
