/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.pestannas.formas;

/**
 *
 * @author josue
 */
public class Bienvenido extends javax.swing.JPanel {

    /**
     * Creates new form Bienvenido
     */
    public Bienvenido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosPersonales = new javax.swing.JPanel();
        lblNombreProfesor = new javax.swing.JLabel();
        lblGrado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlEstadisticas = new javax.swing.JPanel();
        lblProyectosTerminales = new javax.swing.JLabel();
        lblArticulosInvestigacion = new javax.swing.JLabel();
        lblServiciosSociales = new javax.swing.JLabel();
        lblPresentacionesCongreso = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        pnlDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));
        pnlDatosPersonales.setToolTipText("");

        lblNombreProfesor.setText("Nombre del Profesor:");

        lblGrado.setText("Grado");

        javax.swing.GroupLayout pnlDatosPersonalesLayout = new javax.swing.GroupLayout(pnlDatosPersonales);
        pnlDatosPersonales.setLayout(pnlDatosPersonalesLayout);
        pnlDatosPersonalesLayout.setHorizontalGroup(
            pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreProfesor)
                    .addComponent(lblGrado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosPersonalesLayout.setVerticalGroup(
            pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNombreProfesor)
                .addGap(18, 18, 18)
                .addComponent(lblGrado)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido al Sistema de Administración de Productos de Trabajo");

        pnlEstadisticas.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos Realizados"));

        lblProyectosTerminales.setText("Proyectos Terminales:");

        lblArticulosInvestigacion.setText("Artículos de Investigación:");

        lblServiciosSociales.setText("Servicios Sociales:");

        lblPresentacionesCongreso.setText("Presentaciones en Congreso:");

        javax.swing.GroupLayout pnlEstadisticasLayout = new javax.swing.GroupLayout(pnlEstadisticas);
        pnlEstadisticas.setLayout(pnlEstadisticasLayout);
        pnlEstadisticasLayout.setHorizontalGroup(
            pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPresentacionesCongreso)
                    .addComponent(lblProyectosTerminales)
                    .addComponent(lblServiciosSociales)
                    .addComponent(lblArticulosInvestigacion))
                .addContainerGap(546, Short.MAX_VALUE))
        );
        pnlEstadisticasLayout.setVerticalGroup(
            pnlEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadisticasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblProyectosTerminales)
                .addGap(32, 32, 32)
                .addComponent(lblArticulosInvestigacion)
                .addGap(32, 32, 32)
                .addComponent(lblServiciosSociales)
                .addGap(28, 28, 28)
                .addComponent(lblPresentacionesCongreso)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(pnlDatosPersonales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(pnlDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(pnlEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblArticulosInvestigacion;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JLabel lblNombreProfesor;
    private javax.swing.JLabel lblPresentacionesCongreso;
    private javax.swing.JLabel lblProyectosTerminales;
    private javax.swing.JLabel lblServiciosSociales;
    private javax.swing.JPanel pnlDatosPersonales;
    private javax.swing.JPanel pnlEstadisticas;
    // End of variables declaration//GEN-END:variables
}
