/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.pestannas.formas;

/**
 *
 * @author josue
 */
public class NuevoArticulo extends javax.swing.JPanel {

    /**
     * Creates new form NuevoArticulo
     */
    public NuevoArticulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlDatosArticulo = new javax.swing.JPanel();
        lblTituloArticulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblRevistaArticulo = new javax.swing.JLabel();
        cmbRevista = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        rbtnPublicado = new javax.swing.JRadioButton();
        rbtnAceptado = new javax.swing.JRadioButton();
        rbtnRevision = new javax.swing.JRadioButton();
        rbtnProceso = new javax.swing.JRadioButton();
        lblProyectoAsociado = new javax.swing.JLabel();
        cmbProyectoAsociado = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblTitulo.setText("Registrar un Nuevo Artículo de Investigación");

        pnlDatosArticulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Artículo"));

        lblTituloArticulo.setText("Título");

        lblRevistaArticulo.setText("Revista");

        cmbRevista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblEstado.setText("Estado");

        rbtnPublicado.setText("Publicado");

        rbtnAceptado.setText("Aceptado");

        rbtnRevision.setText("En Revisión");

        rbtnProceso.setText("En Proceso");

        lblProyectoAsociado.setText("Proyecto Asociado");

        cmbProyectoAsociado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlDatosArticuloLayout = new javax.swing.GroupLayout(pnlDatosArticulo);
        pnlDatosArticulo.setLayout(pnlDatosArticuloLayout);
        pnlDatosArticuloLayout.setHorizontalGroup(
            pnlDatosArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosArticuloLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(rbtnPublicado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(rbtnAceptado)
                .addGap(70, 70, 70)
                .addComponent(rbtnRevision)
                .addGap(66, 66, 66)
                .addComponent(rbtnProceso)
                .addGap(66, 66, 66))
            .addGroup(pnlDatosArticuloLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlDatosArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo)
                    .addGroup(pnlDatosArticuloLayout.createSequentialGroup()
                        .addGroup(pnlDatosArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProyectoAsociado)
                            .addComponent(lblEstado)
                            .addComponent(lblRevistaArticulo)
                            .addComponent(lblTituloArticulo)
                            .addComponent(cmbRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbProyectoAsociado, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDatosArticuloLayout.setVerticalGroup(
            pnlDatosArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosArticuloLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTituloArticulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblRevistaArticulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnPublicado)
                    .addComponent(rbtnAceptado)
                    .addComponent(rbtnRevision)
                    .addComponent(rbtnProceso))
                .addGap(27, 27, 27)
                .addComponent(lblProyectoAsociado)
                .addGap(18, 18, 18)
                .addComponent(cmbProyectoAsociado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        btnRegistrar.setText("Registrar Articulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pnlDatosArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRegistrar))
                    .addComponent(lblTitulo))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addComponent(pnlDatosArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnRegistrar)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbProyectoAsociado;
    private javax.swing.JComboBox<String> cmbRevista;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblProyectoAsociado;
    private javax.swing.JLabel lblRevistaArticulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloArticulo;
    private javax.swing.JPanel pnlDatosArticulo;
    private javax.swing.JRadioButton rbtnAceptado;
    private javax.swing.JRadioButton rbtnProceso;
    private javax.swing.JRadioButton rbtnPublicado;
    private javax.swing.JRadioButton rbtnRevision;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
