/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uam.pvoe.sw.pestannas.formas;

import java.awt.Component;

/**
 *
 * @author alumno38
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedMenu = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();

        tabbedMenu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedMenuStateChanged(evt);
            }
        });
        tabbedMenu.addTab("tab1", jTabbedPane2);
        tabbedMenu.addTab("tab2", jTabbedPane3);
        tabbedMenu.addTab("tab3", jTabbedPane4);
        tabbedMenu.addTab("tab4", jTabbedPane5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabbedMenuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedMenuStateChanged
        int pestannaElegida = 0;
        pestannaElegida = tabbedMenu.getSelectedIndex();
        System.out.println(pestannaElegida);
        
        switch(pestannaElegida){
            case 0: 
                Component compBienvenido = new Bienvenido();
                tabbedMenu.setComponentAt(0,compBienvenido);
            default:
                System.out.println("Hola default");
            
        }
               
        
        
        
        
    }//GEN-LAST:event_tabbedMenuStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane tabbedMenu;
    // End of variables declaration//GEN-END:variables
}
