/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.pvoe.registro.formas;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;
import uam.pvoe.registro.clases.Alumno;
import uam.pvoe.registro.clases.Interes;

/**
 *
 * @author alumno37
 */
public class FrmRegistro extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistro
     */
    public FrmRegistro() {
        initComponents();
        agruparRB();
    }

    private void agruparRB(){
        
        bgCultural.add(rbTeatro);
        bgCultural.add(rbDanza);
        bgCultural.add(rbDebate);
        bgCultural.add(rbCine);
        
        bgDeportes.add(rbFutbol);
        bgDeportes.add(rbVoleybol);
        bgDeportes.add(rbBasquetbol);
        
        bgRecreativa.add(rbDibujo);
        bgRecreativa.add(rbAjedrez);
        bgRecreativa.add(rbEscritura);
        bgRecreativa.add(rbFoto);
        
        
        //rbOpcionA.setSelected(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDeportes = new javax.swing.ButtonGroup();
        bgCultural = new javax.swing.ButtonGroup();
        bgRecreativa = new javax.swing.ButtonGroup();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblDeportes = new javax.swing.JLabel();
        rbFutbol = new javax.swing.JRadioButton();
        rbVoleybol = new javax.swing.JRadioButton();
        rbBasquetbol = new javax.swing.JRadioButton();
        lblCultural = new javax.swing.JLabel();
        rbTeatro = new javax.swing.JRadioButton();
        rbDanza = new javax.swing.JRadioButton();
        rbDebate = new javax.swing.JRadioButton();
        rbCine = new javax.swing.JRadioButton();
        lblRecreativa = new javax.swing.JLabel();
        rbDibujo = new javax.swing.JRadioButton();
        rbAjedrez = new javax.swing.JRadioButton();
        rbEscritura = new javax.swing.JRadioButton();
        rbFoto = new javax.swing.JRadioButton();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setText("Nombre");

        lblMatricula.setText("Matricula");

        lblDeportes.setText("Deportes");

        rbFutbol.setText("Futbol");

        rbVoleybol.setText("Voleybol");

        rbBasquetbol.setText("Basquetbol");

        lblCultural.setText("Cultural");

        rbTeatro.setText("Teatro");

        rbDanza.setText("Danza");

        rbDebate.setText("Debate");

        rbCine.setText("Cine");

        lblRecreativa.setText("Recreativa");

        rbDibujo.setText("Dibujo");

        rbAjedrez.setText("Ajedrez");

        rbEscritura.setText("Escritura");

        rbFoto.setText("Foto");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblNombre)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                        .addComponent(lblMatricula)
                        .addComponent(txtMatricula))
                    .addComponent(lblDeportes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbFutbol)
                        .addGap(18, 18, 18)
                        .addComponent(rbVoleybol)
                        .addGap(34, 34, 34)
                        .addComponent(rbBasquetbol))
                    .addComponent(lblCultural)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbTeatro)
                        .addGap(18, 18, 18)
                        .addComponent(rbDanza)
                        .addGap(34, 34, 34)
                        .addComponent(rbDebate)
                        .addGap(18, 18, 18)
                        .addComponent(rbCine))
                    .addComponent(lblRecreativa)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbDibujo)
                        .addGap(18, 18, 18)
                        .addComponent(rbAjedrez)
                        .addGap(34, 34, 34)
                        .addComponent(rbEscritura)
                        .addGap(18, 18, 18)
                        .addComponent(rbFoto)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDeportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFutbol)
                    .addComponent(rbVoleybol)
                    .addComponent(rbBasquetbol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCultural)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTeatro)
                    .addComponent(rbDanza)
                    .addComponent(rbDebate)
                    .addComponent(rbCine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRecreativa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDibujo)
                    .addComponent(rbAjedrez)
                    .addComponent(rbEscritura)
                    .addComponent(rbFoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnEnviar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        Alumno al = new Alumno();
            al.setNombre(txtNombre.getText());
            al.setMatricula(txtMatricula.getText());
        
            Interes in = new Interes();
        
        
        Enumeration<AbstractButton> grupo = bgCultural.getElements();        
            while(grupo.hasMoreElements()){
                JRadioButton btnAux = (JRadioButton)grupo.nextElement();
                if(btnAux.isSelected()){
                    in.setCulturales(btnAux.getText());
                    break;
                }
            }
            
        grupo = bgDeportes.getElements();        
            while(grupo.hasMoreElements()){
                JRadioButton btnAux = (JRadioButton)grupo.nextElement();
                if(btnAux.isSelected()){
                    in.setDeportivos(btnAux.getText());
                    break;
                }
            }    
            
        grupo = bgRecreativa.getElements();        
            while(grupo.hasMoreElements()){
                JRadioButton btnAux = (JRadioButton)grupo.nextElement();
                if(btnAux.isSelected()){
                    in.setRecreativos(btnAux.getText());
                    break;
                }
            }    
            
        al.setIntereses(in);
        System.out.println(al);
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCultural;
    private javax.swing.ButtonGroup bgDeportes;
    private javax.swing.ButtonGroup bgRecreativa;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblCultural;
    private javax.swing.JLabel lblDeportes;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRecreativa;
    private javax.swing.JRadioButton rbAjedrez;
    private javax.swing.JRadioButton rbBasquetbol;
    private javax.swing.JRadioButton rbCine;
    private javax.swing.JRadioButton rbDanza;
    private javax.swing.JRadioButton rbDebate;
    private javax.swing.JRadioButton rbDibujo;
    private javax.swing.JRadioButton rbEscritura;
    private javax.swing.JRadioButton rbFoto;
    private javax.swing.JRadioButton rbFutbol;
    private javax.swing.JRadioButton rbTeatro;
    private javax.swing.JRadioButton rbVoleybol;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
